function buildPoster(title, genre, primary, secondary) {
  const safeTitle = (title || 'Película').replace(/&/g, '&amp;');
  const safeGenre = (genre || 'Cine').replace(/&/g, '&amp;');
  const svg = `
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 750" role="img" aria-label="Poster de ${safeTitle}">
      <defs>
        <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0%" stop-color="${primary}"/>
          <stop offset="100%" stop-color="${secondary}"/>
        </linearGradient>
      </defs>
      <rect width="500" height="750" fill="#070b12"/>
      <rect x="0" y="0" width="500" height="750" fill="url(#bg)" opacity="0.82"/>
      <rect x="26" y="26" width="448" height="698" rx="22" fill="rgba(9,12,18,0.25)" stroke="rgba(255,255,255,0.32)"/>
      <circle cx="382" cy="160" r="118" fill="rgba(255,255,255,0.08)"/>
      <circle cx="116" cy="560" r="140" fill="rgba(17,24,39,0.3)"/>
      <text x="250" y="305" text-anchor="middle" fill="#eef3ff" font-family="Arial, sans-serif" font-size="34" font-weight="700" letter-spacing="3">${safeTitle}</text>
      <text x="250" y="355" text-anchor="middle" fill="rgba(238,243,255,0.85)" font-family="Arial, sans-serif" font-size="14" font-weight="600" letter-spacing="2">${safeGenre}</text>
      <text x="250" y="615" text-anchor="middle" fill="#ffffff" font-family="Arial, sans-serif" font-size="12" letter-spacing="7">CINEMATIC PULSE</text>
    </svg>
  `;

  return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`;
}

function buildBackdrop(title, primary, secondary) {
  const safeTitle = (title || 'Película').replace(/&/g, '&amp;');
  const svg = `
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1600 900" role="img" aria-label="Fondo de ${safeTitle}">
      <defs>
        <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0%" stop-color="${primary}"/>
          <stop offset="100%" stop-color="${secondary}"/>
        </linearGradient>
      </defs>
      <rect width="1600" height="900" fill="#05070d"/>
      <rect width="1600" height="900" fill="url(#bg)" opacity="0.82"/>
      <circle cx="1220" cy="220" r="260" fill="rgba(255,255,255,0.08)"/>
      <circle cx="300" cy="660" r="320" fill="rgba(7,11,18,0.35)"/>
      <path d="M0 710 L430 540 L760 670 L1180 440 L1600 610 L1600 900 L0 900 Z" fill="rgba(5,7,13,0.45)"/>
      <text x="120" y="720" fill="#eef3ff" font-family="Arial, sans-serif" font-size="72" font-weight="700" letter-spacing="4">${safeTitle}</text>
    </svg>
  `;

  return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`;
}

const movies = [
  { id: 1, title: 'Inception', year: 2010, genre: 'Acción', duration: '2h 28m', rating: 8.8, description: 'Un ladrón experto entra en los sueños para implantar una idea en la mente de un empresario, desentrañando la frontera entre la realidad y la imaginación.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSZsgrFDm7004Z346AuKu-RNC0gvZ6f1VMS9tRRQLo9Q&s=10", backdrop: "https://m.media-amazon.com/images/M/MV5BZDYwMDU0NTktMjg1MC00ZWNiLWE2ZTQtYzczZWMxZGM3OTJmXkEyXkFqcGc@._V1_.jpg", platforms: { netflix: 'https://www.netflix.com/search?q=Inception', disney: 'https://www.disneyplus.com/search?query=Inception', max: 'https://play.max.com/search?q=Inception' } },
  { id: 2, title: 'Dune', year: 2021, genre: 'Ciencia ficción', duration: '2h 35m', rating: 8.0, description: 'En un futuro lejano, un joven noble debe liderar su pueblo en la lucha por un planeta desértico y su valioso recurso.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDWtljM0rZmkLSaPumXSpbYBxgirQEIcPAbqQoViaghg&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREDu88VavOYZdoRBPIpfyD9_vcCnGqsLzyDAcbd0yClQ&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=Dune', disney: 'https://www.disneyplus.com/search?query=Dune', max: 'https://play.max.com/search?q=Dune' } },
  { id: 3, title: 'Mad Max: Fury Road', year: 2015, genre: 'Acción', duration: '2h 0m', rating: 8.1, description: 'Max Rockatansky y Furiosa unen fuerzas para escapar de un tirano y abrir camino a través del desierto más despiadado.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6zABHT5HQTxUvWV9fIWkRPxPigeR49Nw_g0GL9NilrCZh5733Yg33uZ-3tpwSC87g6fXuVag-Ebidg2_9AeKTF6FoY2jd6u_Xks4II8QDbA&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-Ms9kNRML3Re5xRpVseyqDRZuByi-4i5gbmqEP0qiAYQlMRZPoMKW1auFDIgZXiLs7IJkYeJspGQ7M6k87oHBsDbe_4m8XqRqdoJV36vOvA&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=Mad+Max+Fury+Road', disney: 'https://www.disneyplus.com/search?query=Mad+Max+Fury+Road', max: 'https://play.max.com/search?q=Mad+Max+Fury+Road' } },
  { id: 4, title: 'The Dark Knight', year: 2008, genre: 'Acción', duration: '2h 32m', rating: 9.0, description: 'Batman enfrenta una crisis moral cuando un criminal despiadado intenta sembrar caos en Gotham y poner a prueba su código.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSc9XVUyB6wruir79X_rZSH5R4DCnNuSkYrmBZzeRObwEqrj4CgBZi5DLmidvlBv2b85DEJ0nLGDSP89IOgQOrIRhgBgfbAwJteUv3Ft_meNQ&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGxh1RiUvPhV7W83FApgDAV0j3wvCXj5TTbDukTVGkDA&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=The+Dark+Knight', disney: 'https://www.disneyplus.com/search?query=The+Dark+Knight', max: 'https://play.max.com/search?q=The+Dark+Knight' } },
  { id: 5, title: 'Interstellar', year: 2014, genre: 'Ciencia ficción', duration: '2h 49m', rating: 8.7, description: 'Un equipo de exploradores atraviesa un agujero de gusano para encontrar un planeta habitable y salvar a la humanidad.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiBobMt27ezTFsoBBlOQoMoNz4RBp5KpXyXc1AzOA83g&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfXEVjfmCRPwUaz3cBaiqgiB0u8DgIqLxXfBVynjw22g&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=Interstellar', disney: 'https://www.disneyplus.com/search?query=Interstellar', max: 'https://play.max.com/search?q=Interstellar' } },
  { id: 6, title: 'Arrival', year: 2016, genre: 'Ciencia ficción', duration: '1h 56m', rating: 7.9, description: 'Una lingüista intenta comunicarse con alienígenas que aterrizan en la Tierra, mientras la humanidad se enfrenta a un dilema existencial.', poster:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3XS4JaOR_E2WjTINuzfioH2fY1iV0i04PkhWGdrbFZNcveJHHQpFqsHg&s=10", backdrop:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSVNh70eoq_O2IZx1ldtBKMS4WqnR6JvN6PXgn47nUiA&s" , platforms: { netflix: 'https://www.netflix.com/search?q=Arrival', disney: 'https://www.disneyplus.com/search?query=Arrival', max: 'https://play.max.com/search?q=Arrival' } },
  { id: 7, title: 'The Matrix', year: 1999, genre: 'Ciencia ficción', duration: '2h 16m', rating: 8.7, description: 'Neo descubre que el mundo que conoce es una simulación y se embarca en una rebelión contra las máquinas que lo controlan.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRjkKX3Umz_mScLXi5PaTbeCvPvR4BudnfKMKlqRjFoA&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRjkKX3Umz_mScLXi5PaTbeCvPvR4BudnfKMKlqRjFoA&s=10",platforms: { netflix: 'https://www.netflix.com/search?q=The+Matrix', disney: 'https://www.disneyplus.com/search?query=The+Matrix', max: 'https://play.max.com/search?q=The+Matrix' } },
  { id: 8, title: 'Blade Runner 2049', year: 2017, genre: 'Ciencia ficción', duration: '2h 44m', rating: 8.0, description: 'Un blade runner descubre una verdad que amenaza con cambiar el destino de la humanidad y la propia identidad de la especie.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6a4KOgBrhQsnVMNc3F_IMbOfoNhIfxtD5t1-Ca_294Q&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQIFv3b4BXuB27o_zUM43T8vqdq8qP_7DiM9vK4uATcQ&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=Blade+Runner+2049', disney: 'https://www.disneyplus.com/search?query=Blade+Runner+2049', max: 'https://play.max.com/search?q=Blade+Runner+2049' } },
  { id: 9, title: 'Jurassic World', year: 2015, genre: 'Aventura', duration: '2h 4m', rating: 6.9, description: 'Un parque temático con dinosaurios se convierte en un caos cuando la naturaleza recobra el control y la supervivencia se vuelve incierta.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCuvGGePKs9Tpc9oRUc_2pK44e9RIrEMGaB63NxM0q8w&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgpVa00PBX6QTCJ35k0X8va_M2w-r5dokJJqjsUZEg5A&s=10" ,platforms: { netflix: 'https://www.netflix.com/search?q=Jurassic+World', disney: 'https://www.disneyplus.com/search?query=Jurassic+World', max: 'https://play.max.com/search?q=Jurassic+World' } },
  { id: 10, title: 'Avatar', year: 2009, genre: 'Aventura', duration: '2h 42m', rating: 7.9, description: 'Un marine discapacitado se adentra en Pandora para defender un mundo alienígena y enfrentarse a fuerzas implacables.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVOEduVJm0g_07YhFMbYj2CcIFG9pOnVzdiuYTvp91Bw&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSC3CF16xZLuvfFtt9kquuASvEd60UBGfI1lGyl5MGLsg&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=Avatar', disney: 'https://www.disneyplus.com/search?query=Avatar', max: 'https://play.max.com/search?q=Avatar' } },
  { id: 11, title: 'Oppenheimer', year: 2023, genre: 'Drama', duration: '3h 0m', rating: 8.5, description: 'La historia del físico J. Robert Oppenheimer y la creación de la bomba atómica, con sus consecuencias humanas y políticas.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRr5l-iUkUo-9hlLwOqOBysjHN5EG9gFr8XJc4dLRCEeQ&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-KTNhk7oGFWb9pjqLAAceBSwYtzCvAdcLQhyfrkEaGQ&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=Oppenheimer', disney: 'https://www.disneyplus.com/search?query=Oppenheimer', max: 'https://play.max.com/search?q=Oppenheimer' } },
  { id: 12, title: 'Parasite', year: 2019, genre: 'Thriller', duration: '2h 12m', rating: 8.5, description: 'Una familia pobre se infiltra en la vida de una familia adinerada, desencadenando un juego del que nadie saldrá limpio.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToJ-pi80kIOKSKD1-z4nE7tYWu4sK0zyS8tZEXTu_1nw&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRF5b9mHhIquGECmLGd-22mhfH5Vj-34yn2Gj_r9J1KzQ&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=Parasite', disney: 'https://www.disneyplus.com/search?query=Parasite', max: 'https://play.max.com/search?q=Parasite' } },
  { id: 13, title: 'The Godfather', year: 1972, genre: 'Crimen', duration: '2h 55m', rating: 9.2, description: 'La dinastía criminal Corleone se expande en una historia de ambición, lealtad y poder en la mafia.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjdb_BiwaRCF-HuIYYeN0J_iDB_-mBx4Imll4S9XECNw&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2atGYNx1vi94jVMMnyDtFSjN_5isCOaUWhVYu3mBbRg&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=The+Godfather', disney: 'https://www.disneyplus.com/search?query=The+Godfather', max: 'https://play.max.com/search?q=The+Godfather' } },
  { id: 14, title: 'Fight Club', year: 1999, genre: 'Thriller', duration: '2h 19m', rating: 8.8, description: 'Un consumidor insatisfecho crea un club clandestino de pelea para confrontar su propia ansiedad y su vacío existencial.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTf6DOhdIQQW44khSzKZj5XWoAJqjnmbkz43Mw6AyCmOw&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1w-1SWedx47vIOvQ9JS65bdJoexikEWEvdXiCY4jjmA&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=Fight+Club', disney: 'https://www.disneyplus.com/search?query=Fight+Club', max: 'https://play.max.com/search?q=Fight+Club' } },
  { id: 15, title: 'Whiplash', year: 2014, genre: 'Drama', duration: '1h 47m', rating: 8.5, description: 'Un joven baterista es empujado al extremo por un instructor brutal, en una carrera implacable por la perfección.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSijXNcXbw4DuwAVryajMg-5RMCoYz_3pWxaOqLCXKtg&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxIGS6OZrqGFBKjyTmcpwsDY4-8lZpmLbEeptrJXKWJA&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=Whiplash', disney: 'https://www.disneyplus.com/search?query=Whiplash', max: 'https://play.max.com/search?q=Whiplash' } },
  { id: 16, title: 'La La Land', year: 2016, genre: 'Comedia', duration: '2h 8m', rating: 8.0, description: 'Dos artistas urbanos tienen sueños opuestos pero compartidos, en una historia de amor, música y sacrificio.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYpc4mwJLWyuentijFcVqPGCOFm4jpK3asBPdQub7BxA&s=10", backdrop:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjCzykIP6eo7n1-emC_HNP20W6QxvIbYI8geQ540FMUQ&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=La+La+Land', disney: 'https://www.disneyplus.com/search?query=La+La+Land', max: 'https://play.max.com/search?q=La+La+Land' } },
  { id: 17, title: 'The Lion King', year: 2019, genre: 'Animación', duration: '1h 58m', rating: 6.9, description: 'Un futuro rey debe aceptar su destino y luchar para recuperar el honor de su reino.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlSAmdrBnGMnkooFfySXMU05wACkaC0_2i2EsnaQbuWg&s=10", backdrop:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_f5w0daUJFMuUDkNx_geJ8Ny3zJWS4Xxfms3gldpgdA&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=The+Lion+King', disney: 'https://www.disneyplus.com/search?query=The+Lion+King', max: 'https://play.max.com/search?q=The+Lion+King' } },
  { id: 18, title: 'Spirited Away', year: 2001, genre: 'Animación', duration: '2h 5m', rating: 8.6, description: 'Chihiro se adentra en un mundo mágico donde deberá salvar a sus padres y enfrentarse a criaturas desconocidas.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6_ZMTP-AmWnarhhnLqfSARQzpCthiz-qhJly8ptUfwg&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-v4rnwV5Q0bS-yFUDYqOGYQUEWs9FTMyaAYd-BIW8Tw&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=Spirited+Away', disney: 'https://www.disneyplus.com/search?query=Spirited+Away', max: 'https://play.max.com/search?q=Spirited+Away' } },
  { id: 19, title: 'Frozen', year: 2013, genre: 'Animación', duration: '1h 42m', rating: 7.4, description: 'Una princesa con poderes congelantes debe salvar a su reino y aprender el valor de la verdadera libertad.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZimGmPg9BqSiweMGVFqslrO84mWEcYO9lio0gFstWjg&s=10", backdrop:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmw1mf4l8Xsh5QeYcYPgpphZmT8V-zptD-nvUI5xR5Zg&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=Frozen', disney: 'https://www.disneyplus.com/search?query=Frozen', max: 'https://play.max.com/search?q=Frozen' } },
  { id: 20, title: 'Toy Story', year: 1995, genre: 'Animación', duration: '1h 21m', rating: 8.3, description: 'Una historia luminosa sobre la amistad, la rivalidad y el valor de aceptar que los juguetes tienen su propia vida.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbTvEhXVX22zg-10CRne40OsvgBSZpCUnIpQpc4AW-oA&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnIzSg1QMDIUArWomblV4egrmnBfNoxSyuRzfUojIxFA&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=Toy+Story', disney: 'https://www.disneyplus.com/search?query=Toy+Story', max: 'https://play.max.com/search?q=Toy+Story' } },
  { id: 21, title: 'The Shining', year: 1980, genre: 'Terror', duration: '2h 26m', rating: 8.4, description: 'Un escritor se interna en un hotel aislado, donde la soledad y el horror despiertan su mayor temor.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSU8SNTu9NlU-u1ns62U9MjVLAa7sQrZd5wvmLUJu0gSA&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTp-zOatnGXT2VERlx5bOTqDZFp7EprKkvE7oV8kBm_7g&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=The+Shining', disney: 'https://www.disneyplus.com/search?query=The+Shining', max: 'https://play.max.com/search?q=The+Shining' } },
  { id: 22, title: 'Get Out', year: 2017, genre: 'Terror', duration: '1h 44m', rating: 7.7, description: 'Un joven visita la casa de su pareja y descubre secretos aterradores que cambian su vida para siempre.', poster:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbM6WTVc48wSlDX1ds2TbSMfXRiN7nD5tcyN7YvlIX8w&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgBwfhVvY2KuvbubB55VdEfXGhzzWWKgLvaqtaU5HeJA&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=Get+Out', disney: 'https://www.disneyplus.com/search?query=Get+Out', max: 'https://play.max.com/search?q=Get+Out' } },
  { id: 23, title: 'A Quiet Place', year: 2018, genre: 'Terror', duration: '1h 30m', rating: 7.5, description: 'Una familia debe vivir en silencio para sobrevivir a criaturas que cazan por el sonido.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeTBuYyUdULC1J956_MSCBEQZ6uRPFneiZ6hRSQWCR-g&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUEr3LbgOO-v87NSLeqV83UY773PRb8h8n9I_YYKUjtQ&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=A+Quiet+Place', disney: 'https://www.disneyplus.com/search?query=A+Quiet+Place', max: 'https://play.max.com/search?q=A+Quiet+Place' } },
  { id: 24, title: 'The Conjuring', year: 2013, genre: 'Terror', duration: '1h 52m', rating: 7.5, description: 'Dos investigadores paranormales ayudan a una familia que sufre fenómenos sobrenaturales aterradores.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3EsGuIvUr1KwkuLsDpb8Z1OYhEh0FgugpRRccYLMeZA&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4apBQ7_x5yP2y7qBtHoce0DOM1SdkBIx8v0j2pIparg&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=The+Conjuring', disney: 'https://www.disneyplus.com/search?query=The+Conjuring', max: 'https://play.max.com/search?q=The+Conjuring' } },
  { id: 25, title: 'It', year: 2017, genre: 'Terror', duration: '2h 15m', rating: 7.4, description: 'Un grupo de niños se enfrenta a una criatura que habita en las profundidades del pueblo de Derry.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRU9kPCuK3mClJIRsGkdgEhlA27oyskdJryoZ97dkxPpA&s=10", backdrop:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5t-FjugsoCc2uf0EICrqrM-hU2u2x_w7jY0CzUgrckw&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=It+2017', disney: 'https://www.disneyplus.com/search?query=It+2017', max: 'https://play.max.com/search?q=It+2017' } },
  { id: 26, title: 'Psycho', year: 1960, genre: 'Thriller', duration: '1h 49m', rating: 8.5, description: 'Tras un robo, una mujer llega a un motel aislado y descubre que la pesadilla aún no ha comenzado.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTm1r6EKRCRGhvBORk3NaQc_0jAN588v1ILLieE7jEDbw&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTYzVCVOhvKRzAGkE3I-u6UnSGWRT8biMUqmgQcBRq6w&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=Psycho', disney: 'https://www.disneyplus.com/search?query=Psycho', max: 'https://play.max.com/search?q=Psycho' } },
  { id: 27, title: 'The Prestige', year: 2006, genre: 'Thriller', duration: '2h 10m', rating: 8.5, description: 'Dos magos rivales se enfrentan en una competencia obsesiva por lograr la ilusión definitiva.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThgGRajzXxPnxvJihSd4jvD7ZLhs7Sm9DDxZ8JQeclZw&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTs0QCLw_cXCnj0JCsUX8tkesZhuET3YxJJjV5Zz43LwQ&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=The+Prestige', disney: 'https://www.disneyplus.com/search?query=The+Prestige', max: 'https://play.max.com/search?q=The+Prestige' } },
  { id: 28, title: 'No Country for Old Men', year: 2007, genre: 'Crimen', duration: '2h 2m', rating: 8.1, description: 'Un cazador de dinero descubre una fortuna y se ve perseguido por un asesino implacable en la frontera texana.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMvz3rNtP-LjV7VhzMAph1RxLhAaY_m9BMp7Ml9R95Bw&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1lS3HQvbH6YD3X6jhH8a093hqcs8mzQlYjOVg690__g&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=No+Country+for+Old+Men', disney: 'https://www.disneyplus.com/search?query=No+Country+for+Old+Men', max: 'https://play.max.com/search?q=No+Country+for+Old+Men' } },
  { id: 29, title: 'The Departed', year: 2006, genre: 'Crimen', duration: '2h 31m', rating: 8.5, description: 'Un policía encubierto y un mafioso infiltrado se enfrentan en una red de engaños y traiciones.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIBSktrEnvcs04i0qSxSIGEKD9EkvMLAManGxxq9shlA&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSm7xQvVazsDW2ueJXpzYy8IGbyT2iGyp7_9k2FcBRH3Q&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=The+Departed', disney: 'https://www.disneyplus.com/search?query=The+Departed', max: 'https://play.max.com/search?q=The+Departed' } },
  { id: 30, title: 'Goodfellas', year: 1990, genre: 'Crimen', duration: '2h 25m', rating: 8.7, description: 'Un joven recluta en la mafia se sumerge en un mundo de poder, violencia y ambición sin límites.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXY7XEs0nkASASdxd7Uki5gAo1LexNn4BcTHh7Uek_XA&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2bRlaW8YVfcuEZuLznzzcvwiDk53Xmpz9LI7ADkkpjQ&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=Goodfellas', disney: 'https://www.disneyplus.com/search?query=Goodfellas', max: 'https://play.max.com/search?q=Goodfellas' } },
  { id: 31, title: 'The Incredibles', year: 2004, genre: 'Animación', duration: '1h 55m', rating: 8.0, description: 'Una familia de superhéroes intenta llevar una vida normal mientras enfrenta un nuevo villano.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSf5608AwCgVDmKQ9TVRKSpcl33UEJVVErI7o4nq5M9sw&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOLK370tk3KjC2MvuYspTs1XVO62HobB91V2LSV34qNw&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=The+Incredibles', disney: 'https://www.disneyplus.com/search?query=The+Incredibles', max: 'https://play.max.com/search?q=The+Incredibles' } },
  { id: 32, title: 'Coco', year: 2017, genre: 'Animación', duration: '1h 45m', rating: 8.4, description: 'Un joven músico emprende un viaje a la tierra de los muertos para entender su historia familiar.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNSSXkLA2C48Sfn6Mki5vjD-Q6JEWMhC1oZeAlLzmqJA&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGgBkLUZ1ubgYzO-iBCUXXGZN1JJN-J8Nwp6bY_Em8Zw&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=Coco', disney: 'https://www.disneyplus.com/search?query=Coco', max: 'https://play.max.com/search?q=Coco' } },
  { id: 33, title: 'Up', year: 2009, genre: 'Animación', duration: '1h 36m', rating: 8.3, description: 'Un anciano viudo embarca en una aventura con un explorador joven para cumplir un sueño tardío.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFeXod5uGub88qgVHhr8VSFpqRfDxhglYO_ns4TgDPIQ&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFJRTKNU6opLD3t4AZbRZrLg9ilI0bgZMPxIK52H9jSA&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=Up', disney: 'https://www.disneyplus.com/search?query=Up', max: 'https://play.max.com/search?q=Up' } },
  { id: 34, title: 'Zootopia', year: 2016, genre: 'Animación', duration: '1h 48m', rating: 8.0, description: 'Una conejita policía se alia con un zorro astuto para resolver un enigma criminal en una ciudad animal.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUmGrw8OekXN8IOKkz1YrqZOfNXn-As-Gt8kpfW_twoQ&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSa2E3n-dg9w2-hhLECxvcKfbWDZPDnvi4CMaNUa7KfEA&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=Zootopia', disney: 'https://www.disneyplus.com/search?query=Zootopia', max: 'https://play.max.com/search?q=Zootopia' } },
  { id: 35, title: 'The Batman', year: 2022, genre: 'Thriller', duration: '2h 56m', rating: 8.3, description: 'Batman investiga una serie de asesinatos que sacuden Gotham mientras la ciudad se hunde en la corrupción.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmBNSUQW3GeZL6hAmEY5uGqO-2CSgF7iHJkY0cg1i7dg&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQs6e1n29A6K2trc3NdUsrkem_vYJ7zmDoRClpZsOaxPg&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=The+Batman', disney: 'https://www.disneyplus.com/search?query=The+Batman', max: 'https://play.max.com/search?q=The+Batman' } },
  { id: 36, title: 'Spider-Man: Into the Spider-Verse', year: 2018, genre: 'Animación', duration: '1h 57m', rating: 8.4, description: 'Miles Morales descubre poderes extraordinarios y se une a una versión alternativa del héroe arácnido.', poster:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfIwwYbyMvqLAs_WnUf7gDm8--GX7Ey-IBFJGp7Zeixg&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEXcJS0tHGQKsx5N2qbD0CP8SXdl02m-dlKjHc78OtEQ&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=Spider-Man+Into+the+Spider-Verse', disney: 'https://www.disneyplus.com/search?query=Spider-Man+Into+the+Spider-Verse', max: 'https://play.max.com/search?q=Spider-Man+Into+the+Spider-Verse' } },
  { id: 37, title: 'Ex Machina', year: 2014, genre: 'Thriller', duration: '1h 48m', rating: 7.7, description: 'Un programador participa en una prueba que revela una inteligencia artificial mucho más humana de lo esperado.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2Cr2dSp_HPULiB2n-r1xMJRd4UYVVW6ZPatGF6SFm5w&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ47TYVoNc323PWlljGUy5Ujbu1LOxC22LLaLgOnNxuPg&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=Ex+Machina', disney: 'https://www.disneyplus.com/search?query=Ex+Machina', max: 'https://play.max.com/search?q=Ex+Machina' } },
  { id: 38, title: 'Tenet', year: 2020, genre: 'Acción', duration: '2h 30m', rating: 7.3, description: 'Un agente secreto intenta desbaratar un plan global donde el tiempo se invierte y cada movimiento exige precisión.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVuzKwze7SogtKrVul6VIGEVS7DSMWLSHKyxprpCTmjA&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQIP22AKieuGNfeMvIkP8f8HCOXcuCU9RHcLi4qnJKFQ&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=Tenet', disney: 'https://www.disneyplus.com/search?query=Tenet', max: 'https://play.max.com/search?q=Tenet' } },
  { id: 39, title: 'The Revenant', year: 2015, genre: 'Drama', duration: '2h 36m', rating: 8.0, description: 'Un explorador abandonado por su equipo lucha por sobrevivir y vengarse en medio de la naturaleza despiadada.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvKVsr0H3ChmOBP0AKVZNkdVESQbwMQFiY8KnqDrsNIg&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJlyvknJZJmXXzQFJieDFLFV8tA_V5DOab_NgUb1x0cg&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=The+Revenant', disney: 'https://www.disneyplus.com/search?query=The+Revenant', max: 'https://play.max.com/search?q=The+Revenant' } },
  { id: 40, title: 'The Social Network', year: 2010, genre: 'Drama', duration: '2h 0m', rating: 7.8, description: 'La historia de la creación de Facebook y la rivalidad que marcó la carrera de dos jóvenes visionarios.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlz4kwILBQ9B7fv3sR7xp8r5EZ4AYggNc3RGejDbu4EA&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHR2n-XwQto9pvouMCmM9pODQd2Vw8RZ_Xc0iZ8JeTkQ&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=The+Social+Network', disney: 'https://www.disneyplus.com/search?query=The+Social+Network', max: 'https://play.max.com/search?q=The+Social+Network' } },
  { id: 41, title: 'The Fast and the Furious', year: 2001, genre: 'Acción', duration: '1h 46m', rating: 6.8, description: 'Un policía encubierto se infiltra en el mundo de las carreras callejeras para investigar una serie de robos.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsdPI33fGLQY6v2WlJW844eb66zYq4bTEKN0_oDL1tog&s=10",backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1ryoexsEkZBXj3Y02-vripSHmi2FZ5xaLhuQtRF55ag&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=The+Fast+and+the+Furious', disney: 'https://www.disneyplus.com/search?query=The+Fast+and+the+Furious', max: 'https://play.max.com/search?q=The+Fast+and+the+Furious' } },
  { id: 42, title: '2 Fast 2 Furious', year: 2003, genre: 'Acción', duration: '1h 47m', rating: 5.9, description: 'Brian O’Conner se une a un viejo amigo para infiltrarse en una organización criminal de Miami.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqieHnBZ5-z_wcbJ_m6mmHEVJzFjYK1UnxTQoNjKtCEw&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRETO3Pm5MvSlmTdobIIhq0UaNSkTHVWb8dhd6d4feI-w&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=2+Fast+2+Furious', disney: 'https://www.disneyplus.com/search?query=2+Fast+2+Furious', max: 'https://play.max.com/search?q=2+Fast+2+Furious' } },
  { id: 43, title: 'The Fast and the Furious: Tokyo Drift', year: 2006, genre: 'Acción', duration: '1h 44m', rating: 6.0, description: 'Un joven estadounidense se muda a Tokio y descubre el mundo de las carreras de drift.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQop-uDXZIXvW0oTKT84zdKzIQMXKefiiYMwp68qqSLOw&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHqlI7koCTu2_x_2joZ_cRZTsb7FIRYOat5IuY7RPPzQ&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=Tokyo+Drift', disney: 'https://www.disneyplus.com/search?query=Tokyo+Drift', max: 'https://play.max.com/search?q=Tokyo+Drift' } },
  { id: 44, title: 'Fast & Furious', year: 2009, genre: 'Acción', duration: '1h 47m', rating: 6.5, description: 'Brian y Dom vuelven a encontrarse mientras investigan una organización criminal.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSI7wOzAefFvalQWtGUP9XDgFKuPF0TZb4hFPHx398Jag&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjsJl93XJcgeEbeDetgXDly85Nk3cWKC-KnOzXU6EM-A&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=Fast+%26+Furious+2009', disney: 'https://www.disneyplus.com/search?query=Fast+%26+Furious+2009', max: 'https://play.max.com/search?q=Fast+%26+Furious+2009' } },
  { id: 45, title: 'Fast Five', year: 2011, genre: 'Acción', duration: '2h 10m', rating: 7.3, description: 'Dom, Brian y su equipo planean un gran golpe en Río de Janeiro mientras son perseguidos por un agente federal.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzPb6K6tlR6AQBu3Vbcyyi8Vtxg5HoI9g0enfZFrSAPQ&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxDMchmzRftLtfC_bEVTYz-ddRzoiO2531QQrOFOpN_Q&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=Fast+Five', disney: 'https://www.disneyplus.com/search?query=Fast+Five', max: 'https://play.max.com/search?q=Fast+Five' } },
  { id: 46, title: 'Fast & Furious 6', year: 2013, genre: 'Acción', duration: '2h 10m', rating: 7.0, description: 'El equipo de Dom se reúne para detener a una peligrosa organización criminal liderada por Owen Shaw.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIcajBh5ZLLfPA_HjcFn83v5dx9cUKCBzBDXMcluOE1g&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROmnEaPyiVNIYLNkAqPOjwUKIdPplE-hqR2CK7qiDcUA&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=Fast+%26+Furious+6', disney: 'https://www.disneyplus.com/search?query=Fast+%26+Furious+6', max: 'https://play.max.com/search?q=Fast+%26+Furious+6' } },
  { id: 47, title: 'Furious 7', year: 2015, genre: 'Acción', duration: '2h 17m', rating: 7.1, description: 'El equipo se enfrenta a Deckard Shaw, quien busca vengarse por lo ocurrido con su hermano.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtnVosCjfx200rBZjbTG1DC6DF5bvSK-8REhP9ueRzzg&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKVOdQnaE7gVr3e3aEOIKODDyRTlcH0jkHyNSKNtexPg&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=Furious+7', disney: 'https://www.disneyplus.com/search?query=Furious+7', max: 'https://play.max.com/search?q=Furious+7' } },
  { id: 48, title: 'The Fate of the Furious', year: 2017, genre: 'Acción', duration: '2h 16m', rating: 6.6, description: 'Dom es obligado a trabajar para una misteriosa criminal, enfrentándose al resto de su equipo.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToOgDYFRXk6di4pg61m4k5EnaUXwfeQiKrMj_lfCqpeA&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRghIXwauNFOgas-SvxmLOpW8QAMGV362kBwb2bMVSLNQ&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=The+Fate+of+the+Furious', disney: 'https://www.disneyplus.com/search?query=The+Fate+of+the+Furious', max: 'https://play.max.com/search?q=The+Fate+of+the+Furious' } },
  { id: 49, title: 'F9: The Fast Saga', year: 2021, genre: 'Acción', duration: '2h 23m', rating: 5.2, description: 'Dom y su equipo deben enfrentarse a Jakob, el hermano de Dom, en una nueva amenaza internacional.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSttbMO0TuJr1DFxobo81JnPn01Ny3yt2V5GhLYwpXc5Q&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQP90eoikNhXUtAoIguvyIAA2u9PUig0YPPRXmrf43qBw&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=F9+The+Fast+Saga', disney: 'https://www.disneyplus.com/search?query=F9+The+Fast+Saga', max: 'https://play.max.com/search?q=F9+The+Fast+Saga' } },
  { id: 50, title: 'Fast X', year: 2023, genre: 'Acción', duration: '2h 21m', rating: 5.7, description: 'Dom y su familia se enfrentan a Dante Reyes, quien busca vengarse por los acontecimientos de Fast Five.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8tW09-B-sh9qN_84zAmGkQZS5rdG0Z_FUFbtwZCgu5w&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFZCqyX3yaDRB5mO6uiXXVLrJn7RRrv_G_0zh3ncMIjQ&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=Fast+X', disney: 'https://www.disneyplus.com/search?query=Fast+X', max: 'https://play.max.com/search?q=Fast+X' } },
  { id: 51, title: 'Fast & Furious Presents: Hobbs & Shaw', year: 2019, genre: 'Acción', duration: '2h 17m', rating: 6.5, description: 'Luke Hobbs y Deckard Shaw deben unir fuerzas para detener una amenaza que pone al mundo en peligro.', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQO2_vDHUr6xyHGzEmmDbTc83BhF6hDmoAFHUl6gj9ATQ&s=10", backdrop: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRU2UuDyRex83q1GMN2a7NewizOvs6Mz3RvOclSO0YLZw&s=10", platforms: { netflix: 'https://www.netflix.com/search?q=Hobbs+%26+Shaw', disney: 'https://www.disneyplus.com/search?query=Hobbs+%26+Shaw', max: 'https://play.max.com/search?q=Hobbs+%26+Shaw' } },
];

const songs = [
  { id: 1, title: 'Nocturne Drift', artist: 'Aster Vale', album: 'Midnight Echoes', cover: './music/covers/placeholder-cover.svg', audio: '' },
  { id: 2, title: 'Velvet Signal', artist: 'Nova Bloom', album: 'Neon Harbor', cover: './music/covers/placeholder-cover.svg', audio: '' },
  { id: 3, title: 'Glass Horizon', artist: 'Lume District', album: 'Afterlight', cover: './music/covers/placeholder-cover.svg', audio: '' }
];
